### ISSUE TITLE
May open source the English version dataSet of detecting incongruity corpus

### ISSUE THREAD

**Issue by iofu728** [david-yoon/detecting-incongruity#1]
Hi Seunghyun Yoon,

I see your paper show that
> Following the above process, we generated the Englishversion of dataset based on a large corpus of 0.12m news articles (Horne et al. 2018). In this paper, we do not report any results from the English version of the dataset for brevity, yet we release the two datasets together on this github page 1 for the research community.

But I don't find it in this repo. May you open source this version corpus? Thx.👹

**Comment by david-yoon** [comment]
Hi,
Thank you for your interests in our research.

We keep having internal discussions on this research that are not limited to the previous scope we showed on the AAAI-19 paper.

The way of preparing dataset from the raw corpus is one of the very important issues in this research.
Through some round of discussions, we've reached the conclusion to maintain another GitHub repository for the dataset. (which may deal with several datasets (English version) and preprocessing methodology)

I'll put the GitHub link as soon as we create the new repository.

Thank you,
David

**Comment by iofu728** [comment]
> Hi,
> Thank you for your interests in our research.
> 
> We keep having internal discussions on this research that are not limited to the previous scope we showed on the AAAI-19 paper.
> 
> The way of preparing dataset from the raw corpus is one of the very important issues in this research.
> Through some round of discussions, we've reached the conclusion to maintain another GitHub repository for the dataset. (which may deal with several datasets (English version) and preprocessing methodology)
> 
> I'll put the GitHub link as soon as we create the new repository.
> 
> Thank you,
> David

Thx for your response, expect your dataset 👻

**Comment by khoaln** [comment]
Hi Seunghyun Yoon,

I'm also doing research on incongruence problems. Your dataset will be very helpful. Have you created the repository for the dataset (English version)?

Thank you very much!

**Comment by david-yoon** [comment]
Hi @khoaln @iofu728 
We're currently preparing an another GitHub repository for the english dataset.
The initial version will be available shortly via the following repository.
https://github.com/sugoiii/detecting-incongruity-dataset-gen

I'm also working on evaluating the aaai-19 model (AHDE) to english dataset (not-released, yet) in "dev-NELA" branch.
I'll keep you posted.

Thank you,
David

**Comment by khoaln** [comment]
> Hi @khoaln @iofu728
> We're currently preparing an another GitHub repository for the english dataset.
> The initial version will be available shortly via the following repository.
> https://github.com/sugoiii/detecting-incongruity-dataset-gen
> 
> I'm also working on evaluating the aaai-19 model (AHDE) to english dataset (not-released, yet) in "dev-NELA" branch.
> I'll keep you posted.
> 
> Thank you,
> David

That's great news! Thanks David!

**Comment by iofu728** [comment]
> Hi @khoaln @iofu728
> We're currently preparing an another GitHub repository for the english dataset.
> The initial version will be available shortly via the following repository.
> https://github.com/sugoiii/detecting-incongruity-dataset-gen
> 
> I'm also working on evaluating the aaai-19 model (AHDE) to english dataset (not-released, yet) in "dev-NELA" branch.
> I'll keep you posted.
> 
> Thank you,
> David

Exciting, thank u for ur work.🌹

**Comment by david-yoon** [comment]
Hi @iofu728 @khoaln ,
Please find the GitHub repository for the English version dataset which is created using NELA 2017 data.
https://github.com/sugoiii/detecting-incongruity-dataset-gen

If you want to run our model (AHDE) with the English version of data, you can use the preprocessed dataset that is compatible with our code.
(sh download_processed_dataset_nela-17.sh) in './data' folder

If you have any question, please let me know it.

Thank you,
David
